# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Hj's Blog
tagline:             '学习记录与分享'
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              黄洁

# Custom vars
version:             1.0.0
